/*
 * vertigo - application development platform
 *
 * Copyright (C) 2013-2023, Vertigo.io, team@vertigo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.studio.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.definitions.DataFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MyDtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données Attachment. */
		Attachment(io.vertigo.studio.domain.stereotype.Attachment.class),
		/** Objet de données Car. */
		Car(io.vertigo.studio.domain.car.Car.class),
		/** Objet de données City. */
		City(io.vertigo.studio.domain.stereotype.City.class),
		/** Objet de données CityDisplay. */
		CityDisplay(io.vertigo.studio.domain.stereotype.CityDisplay.class),
		/** Objet de données Command. */
		Command(io.vertigo.studio.domain.stereotype.Command.class),
		/** Objet de données CommandType. */
		CommandType(io.vertigo.studio.domain.stereotype.CommandType.class),
		/** Objet de données CommandValidation. */
		CommandValidation(io.vertigo.studio.domain.stereotype.CommandValidation.class),
		/** Objet de données Famille. */
		Famille(io.vertigo.studio.domain.famille.Famille.class),
		/** Objet de données MotorType. */
		MotorType(io.vertigo.studio.domain.car.MotorType.class),
		/** Objet de données Record. */
		Record(io.vertigo.studio.domain.security.Record.class),
		/** Objet de données VxFileInfo. */
		VxFileInfo(io.vertigo.studio.domain.fileinfo.VxFileInfo.class);

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de Attachment.
	 */
	public enum AttachmentFields implements DataFieldName<io.vertigo.studio.domain.stereotype.Attachment> {
		/** Propriété 'id'. */
		attId,
		/** Propriété 'Url'. */
		url,
		/** Propriété 'Command'. */
		cmdId
	}

	/**
	 * Enumération des champs de Car.
	 */
	public enum CarFields implements DataFieldName<io.vertigo.studio.domain.car.Car> {
		/** Propriété 'identifiant de la voiture'. */
		id,
		/** Propriété 'Constructeur'. */
		manufacturer,
		/** Propriété 'Modèle'. */
		model,
		/** Propriété 'Descriptif'. */
		description,
		/** Propriété 'Année'. */
		year,
		/** Propriété 'Kilométrage'. */
		kilo,
		/** Propriété 'Prix'. */
		price,
		/** Propriété 'Consommation'. */
		consommation,
		/** Propriété 'Motor type'. */
		mtyCd,
		/** Propriété 'Famille'. */
		famId
	}

	/**
	 * Enumération des champs de City.
	 */
	public enum CityFields implements DataFieldName<io.vertigo.studio.domain.stereotype.City> {
		/** Propriété 'id'. */
		citId,
		/** Propriété 'Label'. */
		label,
		/** Propriété 'Postal code'. */
		postalCode
	}

	/**
	 * Enumération des champs de CityDisplay.
	 */
	public enum CityDisplayFields implements DataFieldName<io.vertigo.studio.domain.stereotype.CityDisplay> {
		/** Propriété 'id'. */
		citId,
		/** Propriété 'Label'. */
		label
	}

	/**
	 * Enumération des champs de Command.
	 */
	public enum CommandFields implements DataFieldName<io.vertigo.studio.domain.stereotype.Command> {
		/** Propriété 'id'. */
		cmdId,
		/** Propriété 'Command type'. */
		ctyId,
		/** Propriété 'City'. */
		citId
	}

	/**
	 * Enumération des champs de CommandType.
	 */
	public enum CommandTypeFields implements DataFieldName<io.vertigo.studio.domain.stereotype.CommandType> {
		/** Propriété 'id'. */
		ctyId,
		/** Propriété 'Label'. */
		label
	}

	/**
	 * Enumération des champs de CommandValidation.
	 */
	public enum CommandValidationFields implements DataFieldName<io.vertigo.studio.domain.stereotype.CommandValidation> {
		/** Propriété 'id'. */
		cvaId,
		/** Propriété 'Signer name'. */
		signerName,
		/** Propriété 'Command'. */
		cmdId
	}

	/**
	 * Enumération des champs de Famille.
	 */
	public enum FamilleFields implements DataFieldName<io.vertigo.studio.domain.famille.Famille> {
		/** Propriété 'identifiant de la famille'. */
		famId,
		/** Propriété 'Libelle'. */
		libelle,
		/** Propriété 'Libelle'. */
		description
	}

	/**
	 * Enumération des champs de MotorType.
	 */
	public enum MotorTypeFields implements DataFieldName<io.vertigo.studio.domain.car.MotorType> {
		/** Propriété 'id'. */
		mtyCd,
		/** Propriété 'Label'. */
		label
	}

	/**
	 * Enumération des champs de Record.
	 */
	public enum RecordFields implements DataFieldName<io.vertigo.studio.domain.security.Record> {
		/** Propriété 'Id'. */
		dosId,
		/** Propriété 'Region'. */
		regId,
		/** Propriété 'Departement'. */
		depId,
		/** Propriété 'Commune'. */
		comId,
		/** Propriété 'Record type'. */
		typId,
		/** Propriété 'Title'. */
		title,
		/** Propriété 'Amount'. */
		amount,
		/** Propriété 'Owner'. */
		utiIdOwner,
		/** Propriété 'State'. */
		etaCd
	}

	/**
	 * Enumération des champs de VxFileInfo.
	 */
	public enum VxFileInfoFields implements DataFieldName<io.vertigo.studio.domain.fileinfo.VxFileInfo> {
		/** Propriété 'Identifiant'. */
		filId,
		/** Propriété 'Nom'. */
		fileName,
		/** Propriété 'Type mime'. */
		mimeType,
		/** Propriété 'Taille'. */
		length,
		/** Propriété 'Date de dernière modification'. */
		lastModified,
		/** Propriété 'data'. */
		fileData
	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
