package ${packageName};

import java.util.List;

import io.vertigo.core.lang.Generated;
import io.vertigo.core.lang.ListBuilder;
import io.vertigo.core.node.definition.Definition;
import io.vertigo.core.node.definition.DefinitionSpace;
import io.vertigo.core.node.definition.SimpleDefinitionProvider;
import io.vertigo.datafactory.collections.definitions.FacetDefinition;
import io.vertigo.datafactory.collections.definitions.FacetDefinition.FacetOrder;
import io.vertigo.datafactory.collections.definitions.FacetedQueryDefinition;
<#if hasRangeFacet>
import io.vertigo.datafactory.collections.definitions.FacetRangeDefinitionSupplier;
</#if>
import io.vertigo.datafactory.collections.definitions.FacetTermDefinitionSupplier;
<#if hasCustomFacet>
import io.vertigo.datafactory.collections.definitions.FacetCustomDefinitionSupplier;
</#if>
import io.vertigo.datamodel.smarttype.definitions.SmartTypeDefinition;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * <p>
 * Mode "facettes sans index" : les données sont chargées en mémoire via
 * CollectionsManager.facetList() et ne sont pas connectées à un moteur de recherche.
 */
@Generated
public final class ${dtDefinition.classSimpleName}FacetDefinitionProvider implements SimpleDefinitionProvider {

	/** {@inheritDoc} */
	@Override
	public List<? extends Definition> provideDefinitions(final DefinitionSpace definitionSpace) {
		<#list facetDefinitions as facetDefinition>
		final FacetDefinition ${facetDefinition.name} = new Facet<#if facetDefinition.isRange()>Range<#elseif facetDefinition.isCustom()>Custom<#else>Term</#if>DefinitionSupplier("${facetDefinition.name}")
				.withDtDefinition("${dtDefinition.dtName}")
				.withFieldName("${facetDefinition.fieldName}")
				.withLabel("${facetDefinition.label}")
				<#if facetDefinition.isMultiSelectable()>
				.withMultiSelectable()
				</#if>
				<#if facetDefinition.isRange()>
				<#list facetDefinition.facetValues as facetValue>
				.withRange("${facetValue.code}", "${facetValue.listFilter}", "${facetValue.label}")
				</#list>
				</#if>
				<#if facetDefinition.isCustom()>
				<#list facetDefinition.facetParams as facetParam>
				.withParams("${facetParam.name}", "${facetParam.value?js_string}")
				</#list>
				</#if>
				.withOrder(FacetOrder.${facetDefinition.order})
				.get(definitionSpace);
		</#list>

		return new ListBuilder<Definition>()
				<#list facetDefinitions as facetDefinition>
				.add(${facetDefinition.name})
				</#list>
				<#list facetedQueryDefinitions as facetedQueryDefinition>
				.add(new FacetedQueryDefinition("${facetedQueryDefinition.queryName}",
						List.of(<#list facetedQueryDefinition.facetDefinitions as facetDefinition>${facetDefinition.name}<#sep>, </#list>),
						definitionSpace.resolve("${facetedQueryDefinition.criteriaSmartType}", SmartTypeDefinition.class),
						${facetedQueryDefinition.listFilterClassName}.class,
						"${facetedQueryDefinition.listFilterBuilderQuery}"<#if facetedQueryDefinition.hasGeoSearch()>,
						"${facetedQueryDefinition.geoSearchQuery}"<#else>,
						null</#if>))
				</#list>
				.build();
	}
}
